version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 2

- package-ecosystem: cargo
  directory: "/example-raft-kv"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 2
